# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Diário Bíblico
email: cristianocezar.logistica@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A tua vida é tua vida

  A tua vida é tua vida, 
  Conhece-a enquanto a tens,
  Não a deixes que seja atirada ao vazio,
  Fica atento! há saídas!

  Não consegues vencer a morte, 
  Mas podes vencer a morte em vida,
  Às vezes.

  Se vais tentar, vá até ao fim!

  Isso significa
  Testar a tua resistência  
  E do quanto queres mesmo fazê-lo,
  E vais fazê-lo.

  Apesar da rejeição 
  E das piores probabilidades,
  Será melhor do que tudo que possas imaginar.

  Se vais tentar, vá até ao fim!
  Vá, vá, vá … até ao fim!

  Vais viver a vida,
  Até ao último sorriso,
  É a única boa batalha!

  É a única boa batalha!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  CristianocOsilva

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
